### ISSUE TITLE
Need test function for testing MCB when accessing a resource

### ISSUE THREAD

**Issue by karlcow** [hallvors/sitecomptester-extension#7]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=844556#c87

**Comment by hallvors** [comment]
It's a bit tricky to do this from JS, but sort of doable from SlimerJS. For this reason, currently I add tests marked testType:'mixed-content-blocking' and the SlimerJS framework does some odd stuff that will mark such tests as failed. Specifically, the httpResources variable defined here:
https://github.com/hallvors/sitecomptester-extension/blob/master/slimertester.js#L11
is filled with URLs of http resources: https://github.com/hallvors/sitecomptester-extension/blob/master/slimertester.js#L298 and finally checked for pass/fail status in https://github.com/hallvors/sitecomptester-extension/blob/master/slimertester.js#L321
